### ISSUE TITLE
Error sending message to event discussion

### ISSUE THREAD

**Issue by tompscanlan** [OpenMeet-Team/openmeet-api#162]
1. Create new user, create a new public group..
2. Go to that group page
3. discussion tab
4. type into leave a comment
5. submit
6. error 500 in the api call

server log:
```
openmeet-api
[31m[Nest] 18 - [39m11/29/2024, 3:40:32 PM [31m ERROR[39m [38;5;3m[ExceptionsHandler] [39m[31minvalid json response body at https://zulip-dev.openmeet.net/api/v1/streams/1849/topic_name reason: Unexpected token < in JSON at position 0[39m
openmeet-api
FetchError: invalid json response body at https://zulip-dev.openmeet.net/api/v1/streams/1849/topic_name reason: Unexpected token < in JSON at position 0
openmeet-api
at /usr/src/app/node_modules/node-fetch/lib/index.js:273:32
openmeet-api
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
openmeet-api
at async ZulipService.deleteAdminStreamTopic (/usr/src/app/dist/zulip/zulip.service.js:238:32)
openmeet-api
at async GroupService.sendGroupDiscussionMessage (/usr/src/app/dist/group/group.service.js:572:13)
```

**Comment by stanislavkhatko** [comment]
Will be fixed with https://github.com/OpenMeet-Team/openmeet-api/pull/157, though there is still an issue when Zulip creates default topic 'channel events' witch I was going to remove right away but seems have to filter out of response instead.
